version: '3.8'

services:
  client:
    build:
      context: ./client
    ports:
      - "3001:80"
    restart: always

  server:
    build:
      context: ./server
    ports:
      - "5001:5001"
    env_file:
      - ./server/.env
    restart: always
